#!/bin/sh

i3lock \
  -i Downloads/Wallpapers/variations/wall_blur.png  \
  -L 1920:1080 \
  --pass-volume-keys \
  --pass-media-keys \
  --pass-screen-keys \
  --pass-power-keys \
  -k \
  --time-str="%H:%M:%S" --date-str="%A, %m %Y" \
  --layout-color=FFFFFF \
  --time-color=FFFFFF \
  --date-color=FFFFFF \
  --greeter-color=FFFFFF \
  -f
# change date to betterlockscreen bersion
#https://help.gnome.org/users/gthumb/stable/gthumb-date-formats.html, refer this
