#!/bin/sh

# add a -e flag for echo when sh is not dash, and remove it for dash
cd ~/Studies/; mpv "$(find -L -type f | grep .m[kl]* | dmenu -i -c -g 2 -l 15 -h 20)"

# to make multi files with dmenu and put them in " "s but zathura doesn't work 
#find -L -type f | grep .pdf | dmenu -i -c -g 2 -l 15 -h 50 | sed ':a;N;$!ba;s/\n/ /g' | sed 's/\.\//"\.\//g'| sed 's/\.pdf/\.pdf"/g' 
